name: 'Collect Daily News'
description: 'Collect daily news from Google News RSS.'
inputs:
  keywords:
    description: 'Multi search keywords.'
    required: true
    default: 'GitHub'
  how-many-days:
    description: 'For how many days you needs news.'
    required: false
    default: '1'
  output-format:
    description: 'Output format.'
    required: false
    default: 'json'
outputs:
  result:
    description: 'News data we got.'
runs:
  using: 'node12'
  main: 'index.js'