name: 'Collect Daily News'
description: 'Collect daily news from Google News RSS.'
inputs:
  keywords:
    description: 'Multi search keywords.'
    required: true
    default: 'GitHub'
  how-many-days:
    description: 'For how many days you needs news.'
    required: true
    default: '1'
outputs:
  result:
    description: 'News data we got.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.keywords }}
    - ${{ inputs.how-many-days }}