on: [push]

jobs:
  operation_test:
    runs-on: ubuntu-latest
    name: Operation test of this action
    steps:
      # Required to checkout when using private actions
      - name: Checkout
        uses: actions/checkout@v2
      - name: Operation test
        id: test
        uses: ./  # Uses an action in the root directory
        with: 
          keywords: "GitHub"
      - name: Get output
        run: echo "${{ steps.test.outputs.result }}"