on: [push]

jobs:
  operation_test:
    runs-on: ubuntu-latest
    name: Operation test of this action
    steps:
      # Required to checkout when using private actions
      - name: Checkout
        uses: actions/checkout@v2
      - name: Actions test
        id: test
        uses: ./  # Uses an action in the root directory
        with: 
          keywords: "Docker"
          how-many-days: "1"
      - name: Slack notification test
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: News
          mrkdwn: "<https://codezine.jp/article/detail/13341|「Kubernetes 1.20」がリリース、11の拡張機能が安定版へ、15の拡張機能がベータ版へ移行 - CodeZine（コードジン）>\n\n<https://www.jiji.com/jc/article?k=000003599.000005875&g=prt|セキュリティコンテストCTFの花形ジャンルpwnableの解説書！ 『解題pwnable セキュリティコンテストに挑戦しよう！』発行! 技術の泉シリーズ、12月の新刊 - 時事通信>\n\n<https://japan.techrepublic.com/article/35163707.htm|「Kubernetes」入門--大規模な展開に最適なコンテナーオーケストレーションシステム - TechRepublic Japan>"