on: [push]

jobs:
  operation_test:
    runs-on: ubuntu-latest
    name: Operation test of this action
    steps:
      # Required to checkout when using private actions
      - name: Checkout
        uses: actions/checkout@v2
      - name: Actions test
        id: test
        uses: ./  # Uses an action in the root directory
        with: 
          keywords: "トランプ,Docker+Hub,AWS+Lambda"
          how-many-days: "5"
          output-format: "mrkdwn"
      - name: Slack notification test
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: ${{ steps.test.outputs.result }}